"""change type field calificacion in Tecnico Table

Revision ID: 44c5854dcabb
Revises: aed06adbc4de
Create Date: 2020-06-01 10:21:56.584957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44c5854dcabb'
down_revision = 'aed06adbc4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tecnico', 'calificacion',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tecnico', 'calificacion',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)
    # ### end Alembic commands ###
