"""Create Models

Revision ID: 45e1bdfdc17e
Revises: 
Create Date: 2020-05-30 10:05:05.853048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e1bdfdc17e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categoria',
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('categoria_id')
    )
    op.create_table('Estado_Servicio',
    sa.Column('estadoServicio_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('estadoServicio_id')
    )
    op.create_table('Usuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Cliente',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('cliente_id')
    )
    op.create_table('Tecnico',
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Numeric(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['Categoria.categoria_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('tecnico_id')
    )
    op.create_table('Telefono',
    sa.Column('telefono_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=25), nullable=False),
    sa.Column('numero', sa.String(length=11), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('telefono_id')
    )
    op.create_table('Direccion',
    sa.Column('direccion_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('indicacion', sa.String(length=255), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['Cliente.cliente_id'], ),
    sa.PrimaryKeyConstraint('direccion_id')
    )
    op.create_table('Servicio',
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estadoServicio_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['Cliente.cliente_id'], ),
    sa.ForeignKeyConstraint(['estadoServicio_id'], ['Estado_Servicio.estadoServicio_id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['Tecnico.tecnico_id'], ),
    sa.PrimaryKeyConstraint('servicio_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Servicio')
    op.drop_table('Direccion')
    op.drop_table('Telefono')
    op.drop_table('Tecnico')
    op.drop_table('Cliente')
    op.drop_table('Usuario')
    op.drop_table('Estado_Servicio')
    op.drop_table('Categoria')
    # ### end Alembic commands ###
