"""username field unique

Revision ID: 74f94c0b82b7
Revises: c78a04b9c317
Create Date: 2020-05-31 21:43:24.767908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74f94c0b82b7'
down_revision = 'c78a04b9c317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'Usuario', ['username'])
    op.drop_column('Usuario', 'nombre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'Usuario', type_='unique')
    op.drop_column('Usuario', 'username')
    # ### end Alembic commands ###
