"""change field indicacion for barrio Direccion Table

Revision ID: 7f22e915646b
Revises: 1e23e2f22de0
Create Date: 2020-05-31 22:46:10.668339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f22e915646b'
down_revision = '1e23e2f22de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Direccion', sa.Column('barrio', sa.String(length=255), nullable=True))
    op.drop_column('Direccion', 'indicacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Direccion', sa.Column('indicacion', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('Direccion', 'barrio')
    # ### end Alembic commands ###
