"""Update Telefono Table

Revision ID: c78a04b9c317
Revises: 3223d4849d9a
Create Date: 2020-05-30 21:04:53.771443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78a04b9c317'
down_revision = '3223d4849d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Direccion', ['direccion'])
    op.create_unique_constraint(None, 'Telefono', ['numero'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Telefono', type_='unique')
    op.drop_constraint(None, 'Direccion', type_='unique')
    # ### end Alembic commands ###
